### ISSUE TITLE
Change WMS in HTML representations

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#124]
Hi, 
is there a way to change the WMS used in the HTML representations? I found #64 pointing in that direction, but no hint on how to do this. Any hints welcome.

Best,
Sebastian

**Comment by azahnen** [comment]
Hi Sebastian,
you can configure that in the file `config-store/settings/ldproxy-wfs3-html/HtmlConfig` in the data folder. The feature is not yet in the manager or the docs.

**Comment by cportele** [comment]
Hi Sebastian,
please note that a WMTS or other tile map server that supports the Google Maps tiling scheme is expected, not a WMS. The reason is performance. Almost all servers that support tiles will support the Google Maps tiling scheme.

Here is an example, if you have data in Germany and you want to use a TopPlus map of the mapping agencies. For the map you only need the last two members.

```
{
  "footerText" : "my footer",
  "legalName" : "Legal notice",
  "legalUrl" : "http://example.com/",
  "privacyName" : "Privacy notice",
  "privacyUrl" : "http://example.com/",
  "leafletUrl" : "http://sgx.geodatenzentrum.de/wmts_topplus_web_open/tile/1.0.0/web_grau/default/WEBMERCATOR/{z}/{y}/{x}.png",
  "leafletAttribution" : "&copy; <a href=\"http://www.bkg.bund.de\" target=\"_new\">Bundesamt f&uuml;r Kartographie und Geod&auml;sie</a> 2017, <a href=\"http://sg.geodatenzentrum.de/web_public/Datenquellen_TopPlus_Open.pdf\" target=\"_new\">Datenquellen</a>"
}
```

Best regards, Clemens

**Comment by schmity** [comment]
Hi Clemens, 
this works fine, thanks! After restarting the container, the map has changed.

Best, 
Sebastian

**Comment by schmity** [comment]
Hi again, 
shall I close this issue or is that something you/the project would rather do?

Best,
Sebastian

**Comment by cportele** [comment]
Please feel free to close issues that have been resolved. I will do it this time :)
