### ISSUE TITLE
OGC API - Features - Collections identifier should be id i.s.o. name

### ISSUE THREAD

**Issue by justb4** [interactive-instruments/ldproxy#141]
## Intro
OGC API - Features IMHO has settled on using `id` i.s.o. `name` to identify `Collections` as in [this example](https://github.com/opengeospatial/ogcapi-features/blob/master/core/openapi/ogcapi-features-1.yaml#L648).

## Problem
`ldproxy WFS3` still uses `name` to identify `Collections`. Found with [GeoHealthCheck](https://geohealthcheck.org) demo. See specific [Resource and Test Report](https://demo.geohealthcheck.org/resource/166?lang=en) for https://www.ldproxy.nrw.de/kataster . We recently changed `name` to `id` in GHC WFS3 probe.

## Solution
Change `name` to `id` for Collections in `ldproxy WFS3` components.

**Comment by cportele** [comment]
Thanks @justb4. The reason is that the NRW API is still based on draft.1 from April 2018. That deployment will be updated in the next month or so to the approved spec. It is not just `name` vs `id`, there are a number of other changes, too, e.g. the `extent`.

We are currently updating ldproxy to fully comply with the approved spec, this should be complete in the next week. An example for an updated deployment is https://services.interactive-instruments.de/t15/daraa/collections/culturepnt?f=json.

**Comment by justb4** [comment]
@cportele thanks for quick reaction. I was also about to point to code, but was only looking at `master` branch. I  now see e.g. that [id is encoded in t15 branch](https://github.com/interactive-instruments/ldproxy/blob/t15/ldproxy-wfs3-core/src/main/java/de/ii/ldproxy/wfs3/core/Wfs3Core.java#L105). You are close to the fire off course :-).

**Comment by cportele** [comment]
Thanks for reporting the issue, much appreciated.

**Comment by cportele** [comment]
This issue has been addressed (since several versions), closing...
