### ISSUE TITLE
add option to drop geometries in feature responses

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#223]
via an additional query parameter, e.g. `geometry=false` or `returnGeometry=false`. Should be part of the building block "projections".

**Comment by cportele** [comment]
We also need to add this to v1.3.

**Comment by azahnen** [comment]
I decided to use `skipGeometry=true`. 

I think `geometry` might be misleading with regard to the filter parameters, I would expect it to be an equals filter.
I decided against `returnGeometry` because in my view it is better design to have boolean parameters with default value `false`.

I also implemented this in `v1.3`, it can be tested in the oneo deployment.
