### ISSUE TITLE
cannot deploy ldproxy on windows 10

### ISSUE THREAD

**Issue by yaozhihang** [interactive-instruments/ldproxy#272]
Hi, 

I am currently trying to deploy the ldproxy on my windows 10 by following the instructions on the webseite here
https://interactive-instruments.github.io/ldproxy/manual/00-deployment.html

The command `docker run -d -p 7080:7080 -v ldproxy_data:/ldproxy/data iide/ldproxy:latest` produced the following error:

```
docker: error pulling image configuration: unknown blob.
```

After switching to v2.1.0 `docker run -d -p 7080:7080 -v ldproxy_data:/ldproxy/data iide/ldproxy:v2.1.0`, everything looks good. The `docker ps` command gives the expected status info 
![image](https://user-images.githubusercontent.com/5942971/95314852-14137900-0892-11eb-840a-f3d47807bdd2.png)

However, after typing the URL `http://localhost:7080/` in my browser, the following errors are shwon in the website:

![image](https://user-images.githubusercontent.com/5942971/95314435-95b6d700-0891-11eb-8395-368d1ac3cb9a.png)

Could you guide me how to solve the issue?

thanks

Zhihang

**Comment by cportele** [comment]
You must have accessed `latest` while we were fixing an issue in our CI pipeline. The `latest` tag should be available again.

The GitHub pages documentation is outdated and we no longer link to it (I guess we should remove the pages until they are updated). The following page is up-to-date: https://github.com/interactive-instruments/ldproxy/blob/master/docs/en/deployment.md

Your deployment is working, but you get the 404 because the ldproxy Manager UI is not part of the current release (it should be back later this month):

> Check that ldproxy is running by opening the URI http://localhost:7080/ in a web browser. Since the ldproxy Manager will only be available in a future version, you should receive a 404 error.

I will update the issue when the ldproxy Manager is included again.

Most of the documentation is currently in German only (https://github.com/interactive-instruments/ldproxy/blob/master/docs/de/README.md), but we are working on the English version. Stay tuned... What we have in English is an example how to set up an API (https://github.com/interactive-instruments/ldproxy/blob/master/demo/vineyards/README.md).

Hope this helps,
Clemens

**Comment by yaozhihang** [comment]
Hi Clemens,

thanks very much for your quick answer. I looking forward to see the updated vesion with ldproxy manager.

have a nice day 

Best regards,

Zhihang
