### ISSUE TITLE
datetime parameter with intervals does not work with string columns

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#282]
Using the `datetime` parameter with an interval returns an error. 

https://demo.ldproxy.net/daraa/collections/TransportationGroundCrv/items?datetime=2010-01-01T00:00:00Z/2012-12-31T23:59:59Z results in the following error:

```text
ERROR [2020-10-23 06:36:28,262]                    daraa - Server Error with ID 4a9d695291fe473e: ERROR: function pg_catalog.overlaps(character varying, character varying, timestamp without time zone, timestamp without time zone) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 368 [9423dc1d-25c2-4a4f-9a3e-fafd20f2fc89] [d.i.l.ogcapi.infra.rest.ExceptionMapper] [dw-180]  
```

**Comment by azahnen** [comment]
The error occurs because the daraa configuration uses string columns as temporal queryables. I am pretty sure this is not a new behaviour, just something we did not test yet. 

It works as expected when the configuration uses proper timestamp or date columns, for example:

https://inspire-nrw.ldproxy.net/luftreinhalteplan/v1/collections/umweltzone/items?datetime=2010-01-01T00:00:00Z/2012-12-31T23:59:59Z

I will test if force casting regardless of the column type works and has no unwanted side effects.

**Comment by cportele** [comment]
Hm, I am pretty sure, I have used `datetime` with the Daraa API in the past and it worked.

By the way, in a CQL expression this already works right now, e.g. https://demo.ldproxy.net/daraa/collections/TransportationGroundCrv/items?filter=ZI001_SDV%20AFTER%202012-12-31. That was used quite a bit in VTP2.

In any case, if `datetime` would not work on such string-valued temporal columns, then an error must be raised, if such a column is declared as DATE/DATETIME in a provider schema.

**Comment by cportele** [comment]
I have tried to change the data type of the column in the daraa dataset and `datetime` indeed works after the change, so I can fix the API by updating the db schema.

But we still need to either support also string columns like in CQL or reject invalid temporal queryables.

**Comment by azahnen** [comment]
If it works or not has nothing to do with CQL, it depends on SQL operators and auto casting. If you used `OVERLAPS` in CQL it would not work either. But `AFTER` is just a `>` in SQL which is also defined for string operands. So if one operand is a timestamp and the other a string, Postgres will just auto cast the timestamp to string.

Like I said above I think the correct solution would be to explicitely cast all operands to timestamp for temporal operations instead of relying on auto casting.

**Comment by cportele** [comment]
Next steps:
* Check, if explicit casts can be used.
* List provider schema requirements for queryables in the documentation

**Comment by azahnen** [comment]
Explicit casts will now be applied if the property is of type `DATETIME` in the provider schema. So the column in the database may be a string, but the property has to be a datetime.

We would then check in #263 that only datetime properties are used as temporal queryables.
