### ISSUE TITLE
timestamps must conform to RFC 3339

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#472]
Temporal properties must include an explicit time zone in the timestamp, but currently timestamps are provided without a timezone from the the feature transformer.

The timezone should be fixed to UTC ('Z') for timestamps returned from the API - at least as a default.

Also, the character between the date and the time has to be 'T', not a blank.

**Comment by azahnen** [comment]
Until now it was a requirement to set a `dateFormat` transformation for temporal properties. So the missing 'Z' and 'T' were most likely due to a missing or erroneous `dateFormat`. Thererore I wouldn't consider this a bug, but a configuration issue.

In #483 the requirement to set  a `dateFormat` transformation for temporal properties has been removed. If no `dateFormat` is set explicitely, the provider applies a default `dateFormat` that returns correct timestamps. (Note that it is still possible to generate invalid timestamps using a custom `dateFormat`.)

Additionally support for time zones has been improved:
- If the db column is of type `timestamp with time zone`, until now the time zone would have been passed through, so the API might have returned a timestamp ending with `+02:00`. Now timestamps are always transformed to UTC, so for example if the db returns `2014-06-30 22:00:00+02:00`, the API will return `2014-06-30T20:00:00Z`.
- If the db column is of type `timestamp without time zone`, the optional `nativeTimeZone` set in the provider is applied. So for example if the db returns `2014-06-30 22:00:00` and `nativeTimeZone` is `Europe/Berlin`, the API will return `2014-06-30T20:00:00Z`.
