### ISSUE TITLE
format xlink:hrefs with configurable pattern

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#53]
For the mapping of xlink:href attributes there should be an additional (mime-type agnostic) field to provide a pattern. That would allow to transform e.g. URNs to URLs by prefixing the URN with a GetFeatureById request URL.
For this use case a special substitution point could be implemented so that the WFS URL does not have to be provided every time. So the default pattern might look like this: {{wfs.byid.url}}{{value}}

**Comment by azahnen** [comment]
The implemented solution supports patterns like this: ```{{wfs-by-id}}{{value}}```
Two issues that came up:
- The ALKIS WFS does not accept the URN in a GetFeatureById request, it expects just the last part of the URN. Therefore we would need regex replacements (#56) to really make use of this.
- Displaying the complete GetFeatureById URL is not pretty, it would be great to just use the original value as label for the link. That could be easily achieved with markdown support (#57) and a pattern like this ```[{{value}}]({{wfs-by.id}}{{value}})```.

**Comment by cportele** [comment]
> The ALKIS WFS does not accept the URN in a GetFeatureById request, it expects just the last part of the URN.

The GetFeatureById request always uses the gml:id, not a feature URI, so this is the expected behaviour. I.e., we need to support a mechanism to select the gml:id-part of the href.

However, it is not really clear to me why the link as published by ldproxy should be a GetFeatureById request URL of the underlying WFS. It should be a URL of the proxy service.

I.e., if an xlink:href is a WFS GetFeatureById request we would also need to extract the gml:id from the request and use it to construct a ldproxy-URL. 

Or am I missing something?

**Comment by azahnen** [comment]
Of course the proxy  URL should used instead of the WFS URL. I will change the implementation accordingly.
