### ISSUE TITLE
upgrade PROJ from 8.2.0 to 9.1.0

### ISSUE THREAD

**Issue by rkoblenzer** [interactive-instruments/ldproxy#654]
Note: Maybe it is a good opportunity to create a PR for the changes made in the PROJ-JNI fork.

**Comment by azahnen** [comment]
@cportele @rkoblenzer 

Our CRS unit tests started to fail after the PROJ upgrade. The tests (at least in CI) always use the recent data from the given PROJ release. I ran the tests successfully with the previous data, so the changes are clearly in the data and not in the code.

There are some changes to domains of validity which I would deem uncritical. The more critical issue is decreased precision for some height transformations, I had to change the precision from `μm` to `mm`. (See [here](https://github.com/interactive-instruments/xtraplatform-spatial/pull/152/commits/3c4b1e85b06e8e0fcbc4fb9ccf182aba1bda47a9) for the changes I made.)

The cause seems to be a different default operation e.g. for `EpsgCrs.of(5555) -> EpsgCrs.of(25832, 7837)`:

**PROJ 8**
```
Inverse of UTM zone 32N + Transformation from DHHN92 height to DHHN2016 height (ballpark vertical transformation) + UTM zone 32N
```

**PROJ 9**
```
Inverse of UTM zone 32N + DHHN92 height to EVRF2007 height (1) + Inverse of DHHN2016 height to EVRF2007 height (1) + UTM zone 32N
```

Existing installations are not affected by this since they continue to use the previous data if not deleted explicitly.

**Comment by cportele** [comment]
From the description it sounds like an improvement in the default operation. The precision of the height transformation will in general be (far) less than `mm` anyhow.

**Comment by azahnen** [comment]
@cportele Well, you created the tests that check for `μm` in interactive-instruments/xtraplatform-spatial#134 ;-) Should we then adjust the tests so that a different precision is used for heights? `cm` or `dm`?

**Comment by cportele** [comment]
@azahnen - I think I merely changed the precision to allow the variations introduced by differences in the AMD and ARM floating point architectures 😄. If we want to reduce the checks to the precision of the operations themselves we would need to study the mathematical aspects of the operations in detail. I think we can leave it as it is and if a test fails we can decide, if it is ok to lower the bar.
