### ISSUE TITLE
Bad request Java RuntimeException when querying wfs

### ISSUE THREAD

**Issue by Yoshidown** [interactive-instruments/ldproxy#716]
### ldproxy Version

3.2.3

### Current Behavior

I have added a wfs service to the ldproxy client. When  using the following url I receive an error.

http://localhost:7080/rest/services/bag_wfs/collections/pand/items?bbox=6.140221866525398%2C52.25835875560776%2C6.1494229226165125%2C52.26474680753151&limit=2&offset=458&f=json.

The error I receive is:

`{
  "status" : 400,
  "title" : "Bad Request",
  "detail" : "Could not parse GML: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonGenerationException: Can not start an array, expecting field name (context: Object)"
}`

However when I change the limit from 2 to 1 in the url above, I receive the normal expected response.

What I think happens is that when a higher limit is specified than the remaining amount of features left within a specific bounding box, the limit is applied as the expected amount of returning features or something like that

### Expected Behavior

Expected behavior is that when I specify a higher limit than that there are features remaining that I get the remaining features.

### Steps to Reproduce

- Add the following WFS to the ldproxy manager:
https://service.pdok.nl/lv/bag/wfs/v2_0?request=getCapabilities&service=WFS
- Execute the urls provided above (change localhost and port number to relevant values)

### Relevant log output

```shell
ldproxy_1  | ! at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
ldproxy_1  | ! at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
ldproxy_1  | ! at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
ldproxy_1  | ! at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
ldproxy_1  | ! at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
ldproxy_1  | ! at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
ldproxy_1  | DEBUG [2022-09-08 13:24:56,248]                  bag_wfs - accept application/problem+json [6f33cd16-2030-4168-9edd-e0dac19c4aac]
ldproxy_1  | DEBUG [2022-09-08 13:24:56,249]                  bag_wfs - content-type Optional[ApiMediaType{type=application/problem+json, label=PROBLEM+JSON, parameter=json, fileExtension=json, qs=1000}] [6f33cd16-2030-4168-9edd-e0dac19c4aac]
ldproxy_1  | DEBUG [2022-09-08 13:24:56,249]                  bag_wfs - Client error, HTTP status 400, Request path /bag_wfs/collections/pand/items?bbox=6.140221866525398%2C52.25835875560776%2C6.1494229226165125%2C52.26474680753151&limit=2&offset=458&
f=json: Could not parse GML: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonGenerationException: Can not start an array, expect
ing field name (context: Object) [6f33cd16-2030-4168-9edd-e0dac19c4aac]
ldproxy_1  | DEBUG [2022-09-08 13:24:56,249]                  bag_wfs - Sending response: 400 Bad Request [6f33cd16-2030-4168-9edd-e0dac19c4aac]
```

**Comment by codehub-rony** [comment]
I had a look into this issue as well.

Bug is possibly caused by the presence of a polygon with an interior boundary/ring in the response of the WFS. 

The above API call to ldproxy produces and logs this [get request](https://service.pdok.nl/lv/bag/wfs/v2_0?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&COUNT=2&STARTINDEX=458&TYPENAMES=bag%3Apand&SRSNAME=EPSG%3A28992&BBOX=206412.3298743357%2C474747.7660263704%2C207033.04251667688%2C475465.0547567339%2CEPSG%3A28992&NAMESPACES=xmlns%28gml%2Chttp%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%29%2Cxmlns%28%2Chttp%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%29%2Cxmlns%28ows%2Chttp%3A%2F%2Fwww.opengis.net%2Fows%2F1.1%29%2Cxmlns%28xlink%2Chttp%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%29%2Cxmlns%28xsi%2Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema-instance%29%2Cxmlns%28fes%2Chttp%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%29%2Cxmlns%28bag%2Chttp%3A%2F%2Fbag.geonovum.nl%29) to the wfs. The response seems valid. However, I noticed one feature having a slightly different geometry definition compared to all other result. 

![image](https://user-images.githubusercontent.com/10270049/189372291-8a88700a-79b8-43d9-8d01-088fd2f82ca4.png)

Which corresponds to this[ feature in the actual dataset](https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=0150100000004546&resultOffset=0&detailsObjectId=0150010000004648&objectId=0150100000004546&geometry.x=206484.6107875&geometry.y=475297.34425213&zoomlevel=7). I tested an API call with a bounding box that includes another feature with an interior ring like [this feature](https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=&resultOffset=0&detailsObjectId=&geometry.x=208375.20244927&geometry.y=476325.05742464&zoomlevel=6&objectId=0150100000059515). It produced the same error

@cportele, not sure whether this is a bug or not (yet) supported?

**Comment by azahnen** [comment]
Thanks for the analysis @codehub-rony, this looks like a bug to me. I will look into it in the coming days.

**Comment by azahnen** [comment]
Should be fixed in `iide/ldproxy:next`.
