### ISSUE TITLE
Paging with filter doesn't work when the filter contains the letters ÆØÅ

### ISSUE THREAD

**Issue by guleri** [interactive-instruments/ldproxy#728]
### ldproxy Version

3.2.4

### Current Behavior

When I set a filter that contains the letters ÆØÅ, like:
https://api.ra.no/rest/services/kulturminner/collections/kulturminner/items?f=html&limit=10&kommune=Ås

The next-url becomes: 
https://api.ra.no/rest/services/kulturminner/collections/kulturminner/items?kommune=Ãs&f=html&limit=10&offset=10

This is only a problem in HTML-mode. It works fine in version 3.2.3, so I guess it might have something to do with this: https://github.com/interactive-instruments/ldproxy/pull/670?

### Expected Behavior

I expected that the filter would stay the same when I clicked on page 2.

### Steps to Reproduce

Go to https://api.ra.no/rest/services/kulturminner/collections/kulturminner/items?f=html&limit=10&kommune=Ås and click on the second page.

**Comment by azahnen** [comment]
Confirmed, can also be reproduced with the demo deployment: https://demo.ldproxy.net/vineyards/collections/vineyards/items?village=%2Aß%2A

The issue we fixed in #670 was that query parameters were decoded twice. We removed the first decoding step, which used `UTF-8`,  and retained the second encoding step, which somehow uses `ISO_8859_1`. So we broke paging for non-Latin-1 characters.

**Comment by azahnen** [comment]
Should be fixed in `iide/ldproxy:next`.
